### ISSUE TITLE
Package dotnet-retire 2.3.2 is not compatible with netcoreapp2.1

### ISSUE THREAD

**Issue by fabich** [RetireNet/dotnet-retire#39]
Hi

After upgrading to version 2.x.x from 1.x.x. I receive the following error:
```
Package dotnet-retire 2.3.2 is ot compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package dotnet-retire 2.3.2 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
```
Am I missing something?

**Comment by johnkors** [comment]
How are you installing it?

**Comment by fabich** [comment]
by adding a reference to the .csproj file:

```
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-retire" Version="2.3.2" />
  </ItemGroup>
```

**Comment by johnkors** [comment]
Ah, ok - so that "older" way of installing tools (project tools) is no longer supported. `dotnet retire` has been converted to the [newer dotnet global tool.](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) as of v2 and up.

Installing global tools are done via `dotnet install -g <tool>` , so `dotnet install -g dotnet-retire` is what you need here.

**Comment by johnkors** [comment]
See also the [readme](https://github.com/RetireNet/dotnet-retire/blob/299c4c411e792bc4104b6d67bc0c9b5662f78cf9/README.md#install)

**Comment by fabich** [comment]
ok I see, thanks
