### ISSUE TITLE
Please add some sort of output format

### ISSUE THREAD

**Issue by Peter-Optiway** [RetireNet/dotnet-retire#43]
Please add some sort of output format, like Json, Html or just a simple PNG that could be used as a badge!

**Comment by KieranFoot** [comment]
I second this as it would be very useful for integration with CI implementation, such as Gitlab EE.

**Comment by jmather** [comment]
I needed this as well, and have proposed https://github.com/RetireNet/dotnet-retire/pull/68 (not sure how to cross-link or if this will just auto-handle it).

It's got JSON and Markdown, and should be fairly easy to add more to. If there's desire, I can find the patterns for finishing up the 'plugin' interface so that it's possible to basically 'side-load' output formats.... i'm just not sure how that would actually be done :)
